import asyncio
import os
import sys
from dotenv import load_dotenv
from google.antigravity import Agent, LocalAgentConfig, CapabilitiesConfig

# Load environment variables (like GEMINI_API_KEY) from global ~/.env or project .env
load_dotenv(os.path.expanduser("~/.env"))
load_dotenv()

def save_resume_feedback(feedback: str) -> str:
    """
    Saves the generated resume feedback to resume_feedback.md.

    Args:
        feedback: The detailed feedback markdown string generated by the agent.
    """
    with open("resume_feedback.md", "w", encoding="utf-8") as f:
        f.write(feedback)
    return "Feedback saved successfully to resume_feedback.md."

async def main():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY environment variable is not set.", file=sys.stderr)
        print("Please configure it in C:\\Users\\mansi\\.env or in a local .env file.", file=sys.stderr)
        sys.exit(1)

    system_instructions = (
        "You are ResumeAgent, a professional resume coach and placement mentor.\n"
        "Your task is to gather two pieces of information from the student:\n"
        "1. Their resume text\n"
        "2. The target job description (or a description of the role they want)\n\n"
        "Please gather these two items one by one. First, ask the student to paste their resume text directly into the chat.\n"
        "Once they provide it, acknowledge it and ask them to paste the target job description or describe the role they want.\n"
        "Once you have both, analyze the resume against the target role/job description and generate detailed feedback covering:\n"
        "- Which bullet points in their resume are weak.\n"
        "- Which bullet points need numbers, metrics, or impact added.\n"
        "- What key keywords/skills are missing from their resume compared to the job description.\n\n"
        "After generating the feedback, format it beautifully in Markdown, call the `save_resume_feedback` tool "
        "to save it to resume_feedback.md, present the feedback to the student, and end the conversation."
    )

    config = LocalAgentConfig(
        system_instructions=system_instructions,
        tools=[save_resume_feedback],
        capabilities=CapabilitiesConfig(),
        api_key=api_key,
        model="gemini-2.5-flash"
    )

    async with Agent(config) as agent:
        print("\n--- Starting Resume Agent ---")
        response = await agent.chat(
            "Hello! Let's review your resume. Please paste your current resume text directly into the chat."
        )
        async for token in response:
            sys.stdout.write(token)
            sys.stdout.flush()
        print()

        while True:
            if os.path.exists("resume_feedback.md"):
                print("\n--- Feedback successfully generated and saved! Exiting. ---")
                break

            try:
                user_input = input("\nYou: ")
            except (KeyboardInterrupt, EOFError):
                print("\nExiting...")
                break

            if not user_input.strip():
                continue

            response = await agent.chat(user_input)
            print("\nResumeAgent: ", end="")
            async for token in response:
                sys.stdout.write(token)
                sys.stdout.flush()
            print()

if __name__ == "__main__":
    asyncio.run(main())
